### ISSUE TITLE
Spotify suddenly Black Screen

### ISSUE THREAD

**Issue by PeriyaThala09** [mrpond/BlockTheSpot#646]
I was able to listen music at Spotify around 4.30AM GMT0800(UTC+8), when i want to listen music again around 5.00AM GMT0800(UTC+8), spotify shows blank screen and cannot listen music.

Tried reinstall spotify using latest build, still same

Spotify version : 1.2.79.427.g80eb4a07

<img width="1926" height="1149" alt="Image" src="https://github.com/user-attachments/assets/8e9f8b5e-4d9e-43c0-90a4-f88a02e51758" />

Left side - Spotify Desktop Application
Right side - Windows settings with spotify version

**Comment by WG-Flykii** [comment]
same, i had to downgrade the version

**Comment by WG-Flykii** [comment]
oki thank you !

**Comment by PeriyaThala09** [comment]
> This happens due to offsets being changed or sum bullshit, to fix it temporarily set Block_Banner to 0

help me to fix by guiding?

**Comment by PeriyaThala09** [comment]
> > > This happens due to offsets being changed or sum bullshit, to fix it temporarily set Block_Banner to 0
> > 
> > 
> > help me to fix by guiding?
> 
> Go on your spot installation folder, and look for config.ini and set Block_Banner=0 that should make the software usable again but it'll have some annoying blank banners on it.
> 
> Also huge thanks for mentioning the version, it's really important so the devs knows which version you had the issue

thanks for the guide

**Comment by dsm-labs** [comment]
still happening to me despite downgrading. spotify force updated even though I had it off in config. oh well. thx for the temp fix tho

**Comment by iulian0512** [comment]
same here

**Comment by DialektischeSyntax** [comment]
> same here

Go into spotify installation folder (%appdata% if you're on Windows) and open the config file, then set 'Block_Banner' to 0, as they said above. It works now for me.

**Comment by rethwl** [comment]
> > > This happens due to offsets being changed or sum bullshit, to fix it temporarily set Block_Banner to 0
> > 
> > 
> > help me to fix by guiding?
> 
> Go on your spot installation folder, and look for config.ini and set Block_Banner=0 that should make the software usable again but it'll have some annoying blank banners on it.
> 
> Also huge thanks for mentioning the version, it's really important so the devs knows which version you had the issue

what if I don't have a config file anywhere in the spotify folder?

**Comment by rethwl** [comment]
> > > > > This happens due to offsets being changed or sum bullshit, to fix it temporarily set Block_Banner to 0
> > > > 
> > > > 
> > > > help me to fix by guiding?
> > > 
> > > 
> > > Go on your spot installation folder, and look for config.ini and set Block_Banner=0 that should make the software usable again but it'll have some annoying blank banners on it.
> > > Also huge thanks for mentioning the version, it's really important so the devs knows which version you had the issue
> > 
> > 
> > what if I don't have a config file anywhere in the spotify folder?
> 
> Dude, you actually need BlockTheSpot in order to even have this file created. If you don't have it, that simply means that you didn't install BlockTheSpot.

i definitely have it installed as i'm getting blackscreen today, guess ill just completely reinstall spotify

**Comment by dsm-labs** [comment]
i just did the manual install so I edited the config file before placing it in my directory so spotify doesnt brute force an update

**Comment by Seeburschbanause** [comment]
Here are the missing banner patch offsets for the latest version. Add them to blockthespot_settings.json (inside "Zip Reader" -> "xpui-snapshot.js"). Don't forget to set Block_Banner back to 1 if you've set it to 0 before:
```
"disable_metric_begin_80eb4a0": {
  "Signature": "function WL(e){py.BrowserMetrics",
  "Value": "function WL(e){/*.BrowserMetrics",
  "Offset": 0,
  "Fill": 0,
  "Address": 385902
},
"disable_metric_end_80eb4a0": {
  "Signature": "gL(t),DL(t)}",
  "Value": "gL(t),DL(*/}",
  "Offset": 0,
  "Fill": 0,
  "Address": 388620
},
"premium_btn_end_80eb4a0": {
  "Signature": "children:r.Ru.get(\"upgrade.button\")})",
  "Value": "children:r.Ru.get(\"upgrade.button\")*/",
  "Offset": 0,
  "Fill": 0,
  "Address": 115323
}
```

**Comment by skltujuh** [comment]
> Here are the missing banner patch offsets for the latest version. Add them to blockthespot_settings.json (inside "Zip Reader" -> "xpui-snapshot.js"). Don't forget to set Block_Banner back to 1 if you've set it to 0 before:
> 
> ```
> "disable_metric_begin_80eb4a0": {
>   "Signature": "function WL(e){py.BrowserMetrics",
>   "Value": "function WL(e){/*.BrowserMetrics",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 385902
> },
> "disable_metric_end_80eb4a0": {
>   "Signature": "gL(t),DL(t)}",
>   "Value": "gL(t),DL(*/}",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 388620
> },
> "premium_btn_end_80eb4a0": {
>   "Signature": "children:r.Ru.get(\"upgrade.button\")})",
>   "Value": "children:r.Ru.get(\"upgrade.button\")*/",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 115323
> }
> ```

this work very well, thx

**Comment by agussnb** [comment]
> I was able to listen music at Spotify around 4.30AM GMT0800(UTC+8), when i want to listen music again around 5.00AM GMT0800(UTC+8), spotify shows blank screen and cannot listen music.
> 
> Tried reinstall spotify using latest build, still same
> 
> Spotify version : 1.2.79.427.g80eb4a07
> 
> <img alt="Image" width="1926" height="1149" src="https://private-user-images.githubusercontent.com/92815671/529665822-8e9f8b5e-4d9e-43c0-90a4-f88a02e51758.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY2NzU3MTYsIm5iZiI6MTc2NjY3NTQxNiwicGF0aCI6Ii85MjgxNTY3MS81Mjk2NjU4MjItOGU5ZjhiNWUtNGQ5ZS00M2MwLTkwYTQtZjg4YTAyZTUxNzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjI1VDE1MTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNGZhMWI4ZTU5YmM3NmI0YTY3MTU3YjJkMmJhY2YzNDM0ZTJiYWYzYmJhZmQ5MDQyN2JjMmUxZTg0MWRjMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bztI5y_keKAAjXIHwH0KfYI4rctiHa2xzhQXETTgu24">
> Left side - Spotify Desktop Application Right side - Windows settings with spotify version



> "disable_metric_begin_80eb4a0": {
>   "Signature": "function WL(e){py.BrowserMetrics",
>   "Value": "function WL(e){/*.BrowserMetrics",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 385902
> },
> "disable_metric_end_80eb4a0": {
>   "Signature": "gL(t),DL(t)}",
>   "Value": "gL(t),DL(*/}",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 388620
> },
> "premium_btn_end_80eb4a0": {
>   "Signature": "children:r.Ru.get(\"upgrade.button\")})",
>   "Value": "children:r.Ru.get(\"upgrade.button\")*/",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 115323
> }

had the same problem as OP, this fixed it, thx!

**Comment by PeriyaThala09** [comment]
> Here are the missing banner patch offsets for the latest version. Add them to blockthespot_settings.json (inside "Zip Reader" -> "xpui-snapshot.js"). Don't forget to set Block_Banner back to 1 if you've set it to 0 before:
> 
> ```
> "disable_metric_begin_80eb4a0": {
>   "Signature": "function WL(e){py.BrowserMetrics",
>   "Value": "function WL(e){/*.BrowserMetrics",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 385902
> },
> "disable_metric_end_80eb4a0": {
>   "Signature": "gL(t),DL(t)}",
>   "Value": "gL(t),DL(*/}",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 388620
> },
> "premium_btn_end_80eb4a0": {
>   "Signature": "children:r.Ru.get(\"upgrade.button\")})",
>   "Value": "children:r.Ru.get(\"upgrade.button\")*/",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 115323
> }
> ```

Thanks for the code and can i know there is any way to get rid "Explore Premium"?
anyone having this issue or i'm the one having this issue?

<img width="1679" height="69" alt="Image" src="https://github.com/user-attachments/assets/1766ad08-d047-45dc-abca-be48dd7ad8dd" />

**Comment by Thund33r** [comment]
> Here are the missing banner patch offsets for the latest version. Add them to blockthespot_settings.json (inside "Zip Reader" -> "xpui-snapshot.js"). Don't forget to set Block_Banner back to 1 if you've set it to 0 before:
> 
> ```
> "disable_metric_begin_80eb4a0": {
>   "Signature": "function WL(e){py.BrowserMetrics",
>   "Value": "function WL(e){/*.BrowserMetrics",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 385902
> },
> "disable_metric_end_80eb4a0": {
>   "Signature": "gL(t),DL(t)}",
>   "Value": "gL(t),DL(*/}",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 388620
> },
> "premium_btn_end_80eb4a0": {
>   "Signature": "children:r.Ru.get(\"upgrade.button\")})",
>   "Value": "children:r.Ru.get(\"upgrade.button\")*/",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 115323
> }
> ```

Big ups mate

**Comment by Beans291** [comment]
> Here are the missing banner patch offsets for the latest version. Add them to blockthespot_settings.json (inside "Zip Reader" -> "xpui-snapshot.js"). Don't forget to set Block_Banner back to 1 if you've set it to 0 before:
> 
> ```
> "disable_metric_begin_80eb4a0": {
>   "Signature": "function WL(e){py.BrowserMetrics",
>   "Value": "function WL(e){/*.BrowserMetrics",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 385902
> },
> "disable_metric_end_80eb4a0": {
>   "Signature": "gL(t),DL(t)}",
>   "Value": "gL(t),DL(*/}",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 388620
> },
> "premium_btn_end_80eb4a0": {
>   "Signature": "children:r.Ru.get(\"upgrade.button\")})",
>   "Value": "children:r.Ru.get(\"upgrade.button\")*/",
>   "Offset": 0,
>   "Fill": 0,
>   "Address": 115323
> }
> ```

Hey is there anyway you can explain it differently? I'm not good with this sort of stuff and i keep messing it up.

**Comment by brainfreezerz** [comment]
Is there a difference between the _blockthespot_settings.json_ and _config.ini_ files in the Spotify folder, and the files with the same names in the BTS master folder? 
I noticed that the two discussed solutions only work if you make the edits in the files within the Spotify folder.
Do the files in the master folder only serve as templates when running the batch file for the first time?

**Comment by Fikus25** [comment]
Can anyone provide me just the whole proper json file that works correctly with final version of Spotify? Thanks

**Comment by thugishumble** [comment]
> > Here are the missing banner patch offsets for the latest version. Add them to blockthespot_settings.json (inside "Zip Reader" -> "xpui-snapshot.js"). Don't forget to set Block_Banner back to 1 if you've set it to 0 before:
> > ```
> > "disable_metric_begin_80eb4a0": {
> >   "Signature": "function WL(e){py.BrowserMetrics",
> >   "Value": "function WL(e){/*.BrowserMetrics",
> >   "Offset": 0,
> >   "Fill": 0,
> >   "Address": 385902
> > },
> > "disable_metric_end_80eb4a0": {
> >   "Signature": "gL(t),DL(t)}",
> >   "Value": "gL(t),DL(*/}",
> >   "Offset": 0,
> >   "Fill": 0,
> >   "Address": 388620
> > },
> > "premium_btn_end_80eb4a0": {
> >   "Signature": "children:r.Ru.get(\"upgrade.button\")})",
> >   "Value": "children:r.Ru.get(\"upgrade.button\")*/",
> >   "Offset": 0,
> >   "Fill": 0,
> >   "Address": 115323
> > }
> > ```
> 
> Hey is there anyway you can explain it differently? I'm not good with this sort of stuff and i keep messing it up.

copy the whole thing, go to the settings json file, find "xpui-snapshot.js", paste the text just below the "}," (which is below the adress), align the the text you pasted with the text below it so that they are ordered with the same spacing and make sure to put a comma at the final } of the text you pasted

<img width="863" height="775" alt="Image" src="https://github.com/user-attachments/assets/9123b5b2-f1ab-4f75-b1ec-c916b84fab3a" />

**Comment by Fikus25** [comment]
> > > Here are the missing banner patch offsets for the latest version. Add them to blockthespot_settings.json (inside "Zip Reader" -> "xpui-snapshot.js"). Don't forget to set Block_Banner back to 1 if you've set it to 0 before:
> > > ```
> > > "disable_metric_begin_80eb4a0": {
> > >   "Signature": "function WL(e){py.BrowserMetrics",
> > >   "Value": "function WL(e){/*.BrowserMetrics",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 385902
> > > },
> > > "disable_metric_end_80eb4a0": {
> > >   "Signature": "gL(t),DL(t)}",
> > >   "Value": "gL(t),DL(*/}",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 388620
> > > },
> > > "premium_btn_end_80eb4a0": {
> > >   "Signature": "children:r.Ru.get(\"upgrade.button\")})",
> > >   "Value": "children:r.Ru.get(\"upgrade.button\")*/",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 115323
> > > }
> > > ```
> > 
> > 
> > Hey is there anyway you can explain it differently? I'm not good with this sort of stuff and i keep messing it up.
> 
> copy the whole thing, go to the settings json file, find "xpui-snapshot.js", paste the text just below the "}," (which is below the adress), align the the text you pasted with the text below it so that they are ordered with the same spacing and make sure to put a comma at the final } of the text you pasted
> 
> <img alt="Image" width="863" height="775" src="https://private-user-images.githubusercontent.com/153244479/530411994-9123b5b2-f1ab-4f75-b1ec-c916b84fab3a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY3NzkwMDgsIm5iZiI6MTc2Njc3ODcwOCwicGF0aCI6Ii8xNTMyNDQ0NzkvNTMwNDExOTk0LTkxMjNiNWIyLWYxYWItNGY3NS1iMWVjLWM5MTZiODRmYWIzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyNlQxOTUxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2RhZjY3OGQ1YzAwYjFmYzBhODI2MmY4ZDdkZDg3YjFhZTMzZmIzZTI4Nzc4NzNjNWE3YmZjZjUyMzVlYTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lPvgfMyCStyutNGrp4gmL9WVypgkHzmp5J99c47w_Z8">

Done but it stills shows the black screen.

**Comment by Beans291** [comment]
> > > Here are the missing banner patch offsets for the latest version. Add them to blockthespot_settings.json (inside "Zip Reader" -> "xpui-snapshot.js"). Don't forget to set Block_Banner back to 1 if you've set it to 0 before:
> > > ```
> > > "disable_metric_begin_80eb4a0": {
> > >   "Signature": "function WL(e){py.BrowserMetrics",
> > >   "Value": "function WL(e){/*.BrowserMetrics",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 385902
> > > },
> > > "disable_metric_end_80eb4a0": {
> > >   "Signature": "gL(t),DL(t)}",
> > >   "Value": "gL(t),DL(*/}",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 388620
> > > },
> > > "premium_btn_end_80eb4a0": {
> > >   "Signature": "children:r.Ru.get(\"upgrade.button\")})",
> > >   "Value": "children:r.Ru.get(\"upgrade.button\")*/",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 115323
> > > }
> > > ```
> > 
> > 
> > Hey is there anyway you can explain it differently? I'm not good with this sort of stuff and i keep messing it up.
> 
> copy the whole thing, go to the settings json file, find "xpui-snapshot.js", paste the text just below the "}," (which is below the adress), align the the text you pasted with the text below it so that they are ordered with the same spacing and make sure to put a comma at the final } of the text you pasted
> 
> <img alt="Image" width="863" height="775" src="https://private-user-images.githubusercontent.com/153244479/530411994-9123b5b2-f1ab-4f75-b1ec-c916b84fab3a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY3Nzk0ODMsIm5iZiI6MTc2Njc3OTE4MywicGF0aCI6Ii8xNTMyNDQ0NzkvNTMwNDExOTk0LTkxMjNiNWIyLWYxYWItNGY3NS1iMWVjLWM5MTZiODRmYWIzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyNlQxOTU5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjQyN2FmOWQ5ZDA4YzFjNzY0YjViNzA1NzdlOGExMDBjNWJhYWQ1NzdjYjhhMTI0MjFkYzI1NDExMzE3MGNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LUjEKgaPyyIlbO7-41n2m0pEUfG5PXIMH-sCLXgFu6M">

Thank you so much! It worked perfectly!

**Comment by abidemi-12** [comment]
> > > Here are the missing banner patch offsets for the latest version. Add them to blockthespot_settings.json (inside "Zip Reader" -> "xpui-snapshot.js"). Don't forget to set Block_Banner back to 1 if you've set it to 0 before:
> > > ```
> > > "disable_metric_begin_80eb4a0": {
> > >   "Signature": "function WL(e){py.BrowserMetrics",
> > >   "Value": "function WL(e){/*.BrowserMetrics",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 385902
> > > },
> > > "disable_metric_end_80eb4a0": {
> > >   "Signature": "gL(t),DL(t)}",
> > >   "Value": "gL(t),DL(*/}",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 388620
> > > },
> > > "premium_btn_end_80eb4a0": {
> > >   "Signature": "children:r.Ru.get(\"upgrade.button\")})",
> > >   "Value": "children:r.Ru.get(\"upgrade.button\")*/",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 115323
> > > }
> > > ```
> > 
> > 
> > Hey is there anyway you can explain it differently? I'm not good with this sort of stuff and i keep messing it up.
> 
> copy the whole thing, go to the settings json file, find "xpui-snapshot.js", paste the text just below the "}," (which is below the adress), align the the text you pasted with the text below it so that they are ordered with the same spacing and make sure to put a comma at the final } of the text you pasted


I cant find the xpui-snapshot.js file and i cant edit the json file. Idk if im slow but can you think of any things that im doing wrong

**Comment by PeriyaThala09** [comment]
> > > Here are the missing banner patch offsets for the latest version. Add them to blockthespot_settings.json (inside "Zip Reader" -> "xpui-snapshot.js"). Don't forget to set Block_Banner back to 1 if you've set it to 0 before:
> > > ```
> > > "disable_metric_begin_80eb4a0": {
> > >   "Signature": "function WL(e){py.BrowserMetrics",
> > >   "Value": "function WL(e){/*.BrowserMetrics",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 385902
> > > },
> > > "disable_metric_end_80eb4a0": {
> > >   "Signature": "gL(t),DL(t)}",
> > >   "Value": "gL(t),DL(*/}",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 388620
> > > },
> > > "premium_btn_end_80eb4a0": {
> > >   "Signature": "children:r.Ru.get(\"upgrade.button\")})",
> > >   "Value": "children:r.Ru.get(\"upgrade.button\")*/",
> > >   "Offset": 0,
> > >   "Fill": 0,
> > >   "Address": 115323
> > > }
> > > ```
> > 
> > 
> > Hey is there anyway you can explain it differently? I'm not good with this sort of stuff and i keep messing it up.
> 
> copy the whole thing, go to the settings json file, find "xpui-snapshot.js", paste the text just below the "}," (which is below the adress), align the the text you pasted with the text below it so that they are ordered with the same spacing and make sure to put a comma at the final } of the text you pasted
> 
> <img alt="Image" width="863" height="775" src="https://private-user-images.githubusercontent.com/153244479/530411994-9123b5b2-f1ab-4f75-b1ec-c916b84fab3a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY4MTc2NTIsIm5iZiI6MTc2NjgxNzM1MiwicGF0aCI6Ii8xNTMyNDQ0NzkvNTMwNDExOTk0LTkxMjNiNWIyLWYxYWItNGY3NS1iMWVjLWM5MTZiODRmYWIzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyN1QwNjM1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2I0MzZmODU0YjlkZTM5ZmY3OWVlOTdiODUzNDc1ZjlmZTZjNzQ3OTQ5OGM4MDcwOGQ5ZjA2MjQ0YmMxMDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sd3NqPNbUqZHw7dLnelzSQcmnX0R0xqnZoP7PnJmpMY">

i had tried this but it still shows black screen, anyone can guide us step-by-step? it will help for others who are not familiar or new to this

**Comment by willy25519** [comment]
Here’s the updated file. Replace the one in the “%APPDATA%\Spotify” folder with this and it should work.

[blockthespot_settings.json](https://github.com/user-attachments/files/24353761/blockthespot_settings.json)

**Comment by Fikus25** [comment]
> Here’s the updated file. Replace the one in the “%APPDATA%\Spotify” folder with this and it should work.
> 
> [blockthespot_settings.json](https://github.com/user-attachments/files/24353761/blockthespot_settings.json)

Thanks, it works great now!

**Comment by PeriyaThala09** [comment]
> Here’s the updated file. Replace the one in the “%APPDATA%\Spotify” folder with this and it should work.
> 
> [blockthespot_settings.json](https://github.com/user-attachments/files/24353761/blockthespot_settings.json)

Works fine, thanks🙏

**Comment by mrpond** [comment]
fixed Spotify for Windows (64 bit) 1.2.79.427.g80eb4a07

**Comment by lihuelworks** [comment]
Having this issue now on Spotify 1.2.81.264.gb4ad4efa.

**Comment by Itcheesy** [comment]
having the same issue, black screen. I've uninstalled it completly and reinstalled it through Block The Spot, and changed the conf file for banner to 0 and its still black, what is going on lol?

<img width="1583" height="894" alt="Image" src="https://github.com/user-attachments/assets/f5801af0-e1da-489e-8ba2-87217789fb5d" />

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> having the same issue, black screen. I've uninstalled it completly and reinstalled it through Block The Spot, and changed the conf file for banner to 0 and its still black, what is going on lol?
> 

Just revert to `1.2.80` or `1.2.77` and disable the `update folder`.

When the new patch is out, delete that folder so Spotify can re-create it itself.

**Comment by Itcheesy** [comment]
> > having the same issue, black screen. I've uninstalled it completly and reinstalled it through Block The Spot, and changed the conf file for banner to 0 and its still black, what is going on lol?
> 
> Just revert to `1.2.80` or `1.2.77` and disable the `update folder`.
> 
> When the new patch is out, delete that folder so Spotify can re-create it itself.

how do i revert? sorry im a bit new to all this lol

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> Having this issue now on Spotify 1.2.81.264.gb4ad4efa.

Issue can be merged with https://github.com/mrpond/BlockTheSpot/issues/652

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> > > having the same issue, black screen. I've uninstalled it completly and reinstalled it through Block The Spot, and changed the conf file for banner to 0 and its still black, what is going on lol?
> > 
> > 
> > Just revert to `1.2.80` or `1.2.77` and disable the `update folder`.
> > When the new patch is out, delete that folder so Spotify can re-create it itself.
> 
> how do i revert? sorry im a bit new to all this lol

Uninstall Spotify, download the old version at https://spotify.en.uptodown.com/windows/versions

Install it (without the patch) and run it once. Then completely quit (not minimize, really quit).

Do those commands which will disable the automatic update;

```
1. Close Spotify
2. Open Command Prompt
3. rd /s "%localappdata%\Spotify\Update"
4. mkdir "%localappdata%\Spotify\Update"
5. icacls "%localappdata%\Spotify\Update" /deny "%username%":D
6. icacls "%localappdata%\Spotify\Update" /deny "%username%":R
```

Finally patch it like you used to do.

<img width="1200" height="944" alt="Image" src="https://github.com/user-attachments/assets/926ae578-5d3f-4aaf-97e2-4012dd374279" />

**I have version `1.2.77` at the moment. It tries to download the automatic new version, but that won't work (as intended).**

**Comment by nikomarkx** [comment]
My spot just went black, i've already tried the changing in number, no results.

Any help please? Besides, my spot goes to this one, even if a download the .bat version

<img width="466" height="141" alt="Image" src="https://github.com/user-attachments/assets/c43515ba-7dbd-43ab-9f1a-773126c67298" />

**Comment by EchoAsh-Raziel** [comment]
I installed 1.2.79.427 then it updated automaticlly a few days ago. Later I installed this plugin meet the same issue. The app's window only black, no matter what order I install Spotify or this plug, or how I change the config file.
So here is my temporal solution (I DNK how it works but it works):
1. Like mention above: Uninstall Spotify, download the old version at https://spotify.en.uptodown.com/windows/versions
2. I installed the early 1.2.77 version. If you're not sure is it early enough, then choose earlier.
3. Install the pak you download. Log in then completely exit it. DON'T LET SPOTIFY UPDATE!!!
4. Then automatically install this plugin. Let the plugin help you haddle it, auto update the app or whatever.

**Comment by arthur-adriansens** [comment]
Same problem here. When it went black a couple of months ago, I fixed it with this issue, but now it doesn't work anymore. Downloading an older version doesn't work, and I can't remove the update folder for some reason.

**Comment by 1n3JgKl9pQ6cUMrW** [comment]
> Same problem here. When it went black a couple of months ago, I fixed it with this issue, but now it doesn't work anymore. Downloading an older version doesn't work, and I can't remove the update folder for some reason.

Read the manual https://github.com/mrpond/BlockTheSpot/issues/652#issuecomment-3771835053

First undo the lock of the update folder, than remove the old patch (because the old patch will crash the new patch).

**Comment by JohnShlocker** [comment]
> Uninstall Spotify, download the old version at https://spotify.en.uptodown.com/windows/versions
> 
> Install it (without the patch) and run it once. Then completely quit (not minimize, really quit).
> 
> Do those commands which will disable the automatic update;
> 
> ```
> 1. Close Spotify
> 2. Open Command Prompt
> 3. rd /s "%localappdata%\Spotify\Update"
> 4. mkdir "%localappdata%\Spotify\Update"
> 5. icacls "%localappdata%\Spotify\Update" /deny "%username%":D
> 6. icacls "%localappdata%\Spotify\Update" /deny "%username%":R
> ```
> 
> Finally patch it like you used to do.
> 
> <img alt="Image" width="1200" height="944" src="https://private-user-images.githubusercontent.com/15701574/536412329-926ae578-5d3f-4aaf-97e2-4012dd374279.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjkwOTg1ODAsIm5iZiI6MTc2OTA5ODI4MCwicGF0aCI6Ii8xNTcwMTU3NC81MzY0MTIzMjktOTI2YWU1NzgtNWQzZi00YWFmLTk3ZTItNDAxMmRkMzc0Mjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTIyVDE2MTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MzE4NzRiZTVhZjNhMjMzMWMzNGRhZDk3NWM5YTg2ZDA2OWI0MDVmYmQzNDk4YTY0MGE3YWFiZGZlYTJkNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J5xqdYvG4hH93u07faGKiJe1EZVQUeJ4FcSLvTbrwRE">
> **I have version `1.2.77` at the moment. It tries to download the automatic new version, but that won't work (as intended).**

there is no "Update" folder in the spotify dir

**Comment by Yokenu** [comment]
> > Uninstall Spotify, download the old version at https://spotify.en.uptodown.com/windows/versions
> > Install it (without the patch) and run it once. Then completely quit (not minimize, really quit).
> > Do those commands which will disable the automatic update;
> > ```
> > 1. Close Spotify
> > 2. Open Command Prompt
> > 3. rd /s "%localappdata%\Spotify\Update"
> > 4. mkdir "%localappdata%\Spotify\Update"
> > 5. icacls "%localappdata%\Spotify\Update" /deny "%username%":D
> > 6. icacls "%localappdata%\Spotify\Update" /deny "%username%":R
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Finally patch it like you used to do.
> > <img alt="Image" width="1200" height="944" src="https://private-user-images.githubusercontent.com/15701574/536412329-926ae578-5d3f-4aaf-97e2-4012dd374279.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjkwOTg1ODAsIm5iZiI6MTc2OTA5ODI4MCwicGF0aCI6Ii8xNTcwMTU3NC81MzY0MTIzMjktOTI2YWU1NzgtNWQzZi00YWFmLTk3ZTItNDAxMmRkMzc0Mjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTIyVDE2MTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MzE4NzRiZTVhZjNhMjMzMWMzNGRhZDk3NWM5YTg2ZDA2OWI0MDVmYmQzNDk4YTY0MGE3YWFiZGZlYTJkNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J5xqdYvG4hH93u07faGKiJe1EZVQUeJ4FcSLvTbrwRE">
> > **I have version `1.2.77` at the moment. It tries to download the automatic new version, but that won't work (as intended).**
> 
> there is no "Update" folder in the spotify dir

Found the best fix for me was to install the latest 1.2.77 file on the site you liked and follow the manual install instructions on the main page. I couldnt get the commands to work but doing it all manually seemed to fix it. I did use the [2025.9.10.114] release though.
